version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:10.10.5
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      DIRECTUS_APP_CORS_ORIGIN: http://localhost:8055
    
      KEY: "stafko"
      SECRET: "beebit"
      ADMIN_EMAIL: "stafko@example.com"
      ADMIN_PASSWORD: "stafko"
      
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      
      WEBSOCKETS_ENABLED: "true"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173"
      CORS_METHODS: "GET,POST,PATCH,DELETE,PUT"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      CORS_EXPOSED_HEADERS: "Content-Range"
      CORS_CREDENTIALS: "true"
      CORS_MAX_AGE: "18000"
volumes:
  postgres_data:
